### ISSUE TITLE
 Make an action to extract URL from input file

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/github-actions#160]
We have a [workflow](https://github.com/FerretDB/FerretDB/blob/main/.github/workflows/docs-preview.yml) that builds PR with documentation and deploys it to CloudFlare pages for preview. The way to see that preview URL is currently quite cumbersome. We should improve it.

Write a composite action (similar to extract-docker-tag, but much simpler) that reads "deploy.txt" file, extracts the first encountered URL, and sets the output parameter.

Use that action in the FerretDB workflow to use the deployment URL. See references to this issue.

**Comment by KrishnaSindhur** [comment]
Hi, i can pick this up @AlekSi

**Comment by AlekSi** [comment]
Now to the FerretDB part!
