### ISSUE TITLE
Check that the PR title starts with an imperative verb

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/github-actions#167]
https://github.com/FerretDB/github-actions/blob/6484839ddf046d22e9244c0447737a3275d8b7ad/conform-pr/main.go#L243-L251

That function should also check that title start with an imperative verb ("Fix …", not "Fixing …", "Fixed …" or other forms).

We could probably use https://github.com/jdkato/prose/tree/v2 (despite it being archived) and check that the first token has the correct POS tag.

**Comment by chilagrow** [comment]
Thanks @adetunjii for the contribution :hugs:

**Comment by AlekSi** [comment]
Re-opened since we had to revert it in #169
