### ISSUE TITLE
conform-pr: check PR title length

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/github-actions#230]
[conform-pr](https://github.com/FerretDB/github-actions/tree/main/conform-pr) action should check that the PR title (that is used as commit title on squash&merge) is not longer than 72 Unicode runes. That would prevent the truncation of commit messages in the GitHub UI. It also will make our changelogs better.

**Comment by rafiramadhana** [comment]
@AlekSi can I work on this? thanks
