### ISSUE TITLE
Investigate GitHub's GraphQL API

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/github-actions#44]
For #45, we will need to start interacting with GitHub Projects (beta) via GraphQL API: https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects

First, let's try querying that API manually via `gh` tool.

Second, let's investigate what Go modules we should use for that API (probably https://github.com/shurcooL/githubv4?)

Lastly, let's add some code to conform-pr GitHub Action that queries project's iteration for PRs.

**Comment by rumyantseva** [comment]
Project settings query (example):

```graphql
{
	organization(login: "FerretDB") {
		projectNext(number: 3){id title fields(first: 20){totalCount nodes{id name dataType settings}}}
	}
}
```

**Comment by rumyantseva** [comment]
Current state: WiP in a local branch - https://github.com/rumyantseva/github-actions/tree/issue-44-trying-graphql (there are some things to try/discuss)

**Comment by rumyantseva** [comment]
Another interesting thing: if we call GraphQL too often we can reach rate limiting.

**Comment by rumyantseva** [comment]
h3. Main learnings

**Objects and ids**
- PR - `PR_`
- Issue - `I_`
- Project Next (new beta projects) - `PN_`
- Card on a board (project next) - `PNI_` (draft, issue or pull request)
- View in a project next - `PNV_`
- Field in a project next - `PNF_`
- Field values (in cards) - `PNIFV_`
- etc.

**How to find PR id or Issue id from Card**
It works through `content`:
```graphql
{
	user(login: "rumyantseva") {
		
		projectNext(number: 1) {
			id 
			title
			
			items(first: 20) {
				totalCount
				nodes {
					id
					title
					type
					content {
						... on PullRequest  {
								id
						}
						
						... on Issue {
							id
						}
					}

...

				}
			}
		
		}
	}
}
```
