### ISSUE TITLE
Check Sprint field in PRs

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/github-actions#45]
When [conform-pr GitHub Action](https://github.com/FerretDB/github-actions/tree/main/conform-pr) checks some pull request, it should fail if the Sprint field (in all projects where it exists) is empty ~or has a value that is not the "current" one~.

**Comment by AlekSi** [comment]
@ronaudinho Wanna take this one? See https://github.com/FerretDB/github-actions/pull/109#issuecomment-1287666604

**Comment by ronaudinho** [comment]
yes sure, already working on it, will PR soonish @AlekSi
