### ISSUE TITLE
`conform-pr`Action  should check PR description

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/github-actions#49]
It should check that the PR description ends with a dot. In particular, it should not end with whitespace.

**Comment by rumyantseva** [comment]
@AlekSi what if PR description is empty? Should it be considered as valid?

Also, I'll call the checker `checkBody`, not `checkDescription` as in Github API this field is called "body", not "description".

**Comment by rumyantseva** [comment]
<img width="964" alt="Screenshot 2022-05-24 at 12 01 05" src="https://user-images.githubusercontent.com/1684673/170006037-9852b3ca-b275-4c9d-9dad-6280b3c07622.png">

@AlekSi would such output work? Or would you prefer different formatting?

**Comment by rumyantseva** [comment]
Answers:
- Empty description is valid
- Various punctuation is possible (`?`, `!`, etc)
- Leave such formatting for now (we will use md in the future)
