### ISSUE TITLE
Rename `ProjectNext` GraphQL objects to `ProjectV2`

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/github-actions#71]
https://github.blog/changelog/2022-06-23-the-new-github-issues-june-23rd-update/

That should be as simple as renaming.

**Comment by AlekSi** [comment]
#80 was reverted

**Comment by rumyantseva** [comment]
I have a branch here https://github.com/rumyantseva/github-actions/tree/fix-pr-query
