### ISSUE TITLE
Read organization members

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/github-actions#90]
Some Conform PR checks will be different between PRs from the community and FerretDB organization members. We should read organization members and check if the PR author belongs to it.

**Comment by astitva0011** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?

**Comment by AlekSi** [comment]
@astitva0011 any news?

**Comment by AlekSi** [comment]
There is an API to read org members: https://docs.github.com/en/rest/orgs/members#list-organization-members
It can be accessed by https://pkg.go.dev/github.com/google/go-github/v48/github#OrganizationsService.ListOrgMemberships
It should be called there: https://github.com/FerretDB/github-actions/blob/main/conform-pr/main.go

**Comment by AlekSi** [comment]
@astitva0011 any news?
